language: c
compiler:
  - gcc
  - clang
before_install:
 - sudo apt-get install check

# Change this to your needs
script: 
  - ./bootstrap.sh
  - ./configure --with-check && make && make check

after_success: ./update_pages.sh
